clickhouse-client < 1-most-pop.sql
clickhouse-client < 2-most-pop.sql
clickhouse-client < 3-cities-departure.sql
clickhouse-client < 4-flight-delay.sql
clickhouse-client < 5-cities-departure.sql
clickhouse-client < 6-flight-max-duration.sql
clickhouse-client < 7-distribution-arrival.sql
clickhouse-client < 8-air-companies-stop.sql
clickhouse-client < 9-most-trending-dest.sql
clickhouse-client < A-most-popularity-cities.sql
